<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="icon" href="<?php echo $img; ?>/EC_Logo.png">
    
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php gettitle(); ?></title>
        <!--[if lt IE 9]>
                <script src="js/html5shiv.js"></script>
                <script src="js/respond.min.js"></script>
        <![endif]-->
        <link rel="stylesheet" href="<?php echo $css; ?>/bootstrap.min.css">
        <link rel="stylesheet" href="<?php echo $css; ?>/font-awesome.min.css">
         <link rel="stylesheet" href="<?php echo $css; ?>/jquery-ui.min.css">
         <link rel="stylesheet" href="<?php echo $css; ?>/jquery.selectBoxIt.css">
        <link rel="stylesheet" href="<?php echo $css; ?>/mystyle.css">
  
        
    </head>
    <body>