

     <script src="<?php echo $js;?>/jquery-3.2.1.min.js"></script>
     <script src="<?php echo $js;?>/jquery-ui.min.js"></script>
     <script src="<?php echo $js; ?>/bootstrap.min.js"></script>
     <script src="<?php echo $js; ?>/choosen.js"></script>
     <!-- <script src="<?php echo $js; ?>/jqueryajax.js"></script>
      <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script> -->
    <script src="<?php echo $js; ?>/jquery/jRating.jquery.min.js"></script>
     <script src="<?php echo $js; ?>/jquery.selectBoxIt.min.js"></script>
     <script src="<?php echo $js; ?>/ajaxtest.js"></script>
     <script src="<?php echo $js; ?>/tag-it.min.js"></script>

     <script src="<?php echo $js; ?>/myjs.js"></script>
    </body>
</html>